# Generated by Django 6.1 on 2026-08-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='marks_awarded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='results_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
