# Generated by Django 6.1 on 2026-08-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_proctoringlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringlog',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='proctoring_screenshots/'),
        ),
    ]
