# Generated by Django 6.1 on 2026-08-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_proctoringlog_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proctoringlog',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='proctoringlog',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='proctoring_evidence/'),
        ),
    ]
