# Generated by Django 6.1 on 2026-08-25 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_remove_proctoringlog_screenshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio', models.FileField(upload_to='proctoring_audio/')),
                ('chunk_number', models.PositiveIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_recordings', to='exams.submission')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
    ]
