# Generated by Django 6.1 on 2026-08-25 10:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_audiorecording'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAudioRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to='proctoring_full_audio/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='full_audio_recording', to='exams.submission')),
            ],
        ),
        migrations.DeleteModel(
            name='AudioRecording',
        ),
    ]
