# Generated by Django 6.1 on 2026-08-25 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_examaudiorecording_delete_audiorecording'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamVideoRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', models.FileField(upload_to='proctoring_videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_recording', to='exams.submission')),
            ],
        ),
    ]
