# Generated by Django 6.1 on 2026-08-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_examvideorecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='whiteboard_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
